### ISSUE TITLE
Pinhole_Intrinsic constructor using Matrix

### ISSUE THREAD

**Issue by jkerfs** [openMVG/openMVG#770]
My application requires that I initialize various subclasses of `Pinhole_Intrinsic` (`Pinhole_Intrinsic_Radial_K3`, `Pinhole_Intrinsic_Brown_T2`, etc.) using calibrations from ROS/OpenCV  like the one below (camera.yaml):

```
image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [793.9539661935881, 0, 346.6674464310099, 0, 803.5395377886039, 286.0850718330775, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.01948322754117298, 0.1393907310664927, 0.01092723297451327, 0.0002371815960699387, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [805.3073120117188, 0, 345.6016771273698, 0, 0, 812.0440063476562, 288.5004389477708, 0, 0, 0, 1, 0]
```

It would be great for the subclasses of `Pinhole_Intrinsic` to provide constructors that accept an Eigen Matrix since it would be straightforward conversion from the ROS/OpenCV calibration files.  For `Pinhole_Intrinsic` it might look something like this (untested):
```
Pinhole_Intrinsic(unsigned int w = 0, unsigned int h = 0, const Mat3& K ) : IntrinsicBase( w, h )
{
     K_ = K;
     Kinv_ = K_.inverse();
}
```

I already have helper functions that perform these conversions, so it would be trivial to incorporate into the openMVG API.  Is this a feature that would be useful for others?
